'''
myfile = open("test.txt", "w")
myfile.write("This file was generated by Python.\n")
myfile.write("----------------------------------\n")
myfile.write("Hello World!\n")
myfile.close()
'''

filehandle = open("test.txt", "r")
while True:
	theline = filehandle.readline()
	if len(theline) == 0:
		break

	print(theline, end="")

filehandle.close()